### ISSUE TITLE
Доработки

### ISSUE THREAD

**Issue by alexkoss** [DashaArtemieva/SSH-Ansible-LDAP#1]
Добрый день, Дарья! Меня зовут Александр, представитель БалтИнфоКом.

Для проверки вашего задания создал окружение с 2 виртуальными машинами на Ubuntu 22.04.2 lts.
Поменял ip, пользователя, запустил скрипты, не работает.
С какими проблемами я столкнулся:
1) ssh-keygen -t rsa
2) дополнительно установить sshpass
3) не соединялось с целевой машиной без become_user: sentinel, вероятно некорректно прочитался файл hosts
4) не запускается основной скрипт установки

Запускаю с управляющей машины командой 
ansible-playbook Install_LDAP.yaml -vvv

Версия:
sentinel@sentinel-vm22:~/test/SSH-Ansible-LDAP/SSH-Ansible-LDAP-main$ ansible-playbook --version
ansible-playbook 2.10.8
  config file = /home/sentinel/test/SSH-Ansible-LDAP/SSH-Ansible-LDAP-main/ansible.cfg
  configured module search path = ['/home/sentinel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

Предложение следующее:
проверить скрипты на версии ansible 2.10.x, внести необходимые правки, добавить пример запуска, добавить описание возможных дополнительных действий с учётной записью admin1 (например, добавление в sudoers).

Буду рад услышать ваше согласие, если готовы на дальнейшие доработки задания.

**Comment by DashaArtemieva** [comment]
Добрый день, Александр!Интересно доработать)С Уважением, Артемьева Дарья 8(911)7255849Отправлено с iPhone12 мая 2023 г., в 10:06, Alexandr Kossakovskiy ***@***.***> написал(а):﻿
Добрый день, Дарья! Меня зовут Александр, представитель БалтИнфоКом.
Для проверки вашего задания создал окружение с 2 виртуальными машинами на Ubuntu 22.04.2 lts.
Поменял ip, пользователя, запустил скрипты, не работает.
С какими проблемами я столкнулся:

ssh-keygen -t rsa
дополнительно установить sshpass
не соединялось с целевой машиной без become_user: sentinel, вероятно некорректно прочитался файл hosts
не запускается основной скрипт установки

Запускаю с управляющей машины командой
ansible-playbook Install_LDAP.yaml -vvv
Версия:
***@***.***:~/test/SSH-Ansible-LDAP/SSH-Ansible-LDAP-main$ ansible-playbook --version
ansible-playbook 2.10.8
config file = /home/sentinel/test/SSH-Ansible-LDAP/SSH-Ansible-LDAP-main/ansible.cfg
configured module search path = ['/home/sentinel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3/dist-packages/ansible
executable location = /usr/bin/ansible-playbook
python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Предложение следующее:
проверить скрипты на версии ansible 2.10.x, внести необходимые правки, добавить пример запуска, добавить описание возможных дополнительных действий с учётной записью admin1 (например, добавление в sudoers).
Буду рад услышать ваше согласие, если готовы на дальнейшие доработки задания.

**Comment by alexkoss** [comment]
@DashaArtemieva Дарья, когда внесёте правки?

**Comment by DashaArtemieva** [comment]
Добрый день!
Прошу прощения, что так долго (дедлайны в универе).
Поправила настройки в файлах hosts и ansible. У меня авторизация на удаленном хосте проходит по ключу, поэтому не вижу смысла настраивать менее безопасный sshpass. В bash скрипте для уд. хоста включила добавление пользователя в sudoers, а также (и на упр. и на уд.) добавила установку Ansible Core. Запускать скрипты с привилегированными правами.
Подключение у меня происходит при запуске yaml, но спотыкается на настройке атрибутов LDAP. Т.е. он как будто бы успешно устанавливает LDAP и переходит к настройкам, но при ручной проверке на уд. хосте служба не установлена, не понимаю почему.
Файлы в репозитории обновила.
Так же приложила скриншот ошибки.
Если у Вас есть время проверить и подсказать, почему он не устанавливает LDAP, буду очень признательна.

**Comment by alexkoss** [comment]
@DashaArtemieva какой вывод команды 
```
sudo bash Gen_and_send_key_server2.sh
```
?

Конкретнее интересует команда с ssh-copy-id

**Comment by alexkoss** [comment]
@DashaArtemieva в этом и заключается суть тестового задания - сделать самому, чтобы работало по описанному заданию. Ожидаю результата до вечера пятницы.
